# Generated by Django 6.1 on 2026-08-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_user_id", models.CharField(max_length=64, unique=True)),
                ("flagged_count", models.IntegerField(default=0)),
                ("deleted_count", models.IntegerField(default=0)),
                ("last_flagged_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlaggedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_user_id", models.CharField(max_length=64)),
                ("slack_channel_id", models.CharField(max_length=64)),
                ("message_ts", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("toxic", models.FloatField(default=0.0)),
                ("severe_toxic", models.FloatField(default=0.0)),
                ("obscene", models.FloatField(default=0.0)),
                ("threat", models.FloatField(default=0.0)),
                ("insult", models.FloatField(default=0.0)),
                ("identity_hate", models.FloatField(default=0.0)),
                ("max_score", models.FloatField(default=0.0)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("flag", "Flagged"),
                            ("delete", "Deleted"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="moderation__created_0c0897_idx"
                    ),
                    models.Index(
                        fields=["slack_user_id"], name="moderation__slack_u_268e62_idx"
                    ),
                ],
            },
        ),
    ]
