# Generated by Django 6.1 on 2026-08-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaggedmessage",
            name="action_taken",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("flag", "Flagged"),
                    ("flag_high", "Flagged (High Confidence)"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
