# Generated by Django 6.1 on 2026-08-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_alter_flaggedmessage_action_taken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userhistory",
            old_name="deleted_count",
            new_name="high_confidence_count",
        ),
    ]
